" Add line numbers
set number
set relativenumber

" Remaps
inoremap <C-c> <Esc>
nnoremap ; :
vnoremap ; :

" Enable type file detection, enable plugins and load plugin and indent for the detected file type.
filetype plugin indent on

" Turn syntax highlighting on.
syntax on

" Use space characters instead of tabs.
set expandtab

" Set shift width to 4 spaces.
set shiftwidth=4

" Set tab width to 4 columns.
set tabstop=4

" Do not save backup files.
"set nobackup

" Do not let cursor scroll below or above N number of lines when scrolling.
set scrolloff=10

" Set Mouse support
set mouse=a

" Do not wrap lines. Allow long lines to extend as far as the line goes.
" set nowrap

" While searching though a file incrementally highlight matching characters as you type.
set incsearch

" Ignore capital letters during search.
set ignorecase

" Override the ignorecase option if searching for capital letters.
" This will allow you to search specifically for capital letters.
set smartcase

" Show partial command you type in the last line of the screen.
set showcmd

" Show the mode you are on the last line.
set showmode

" Show matching words during a search.
set showmatch

" Use highlighting when doing a search.
set hlsearch

" Terminal colors
set t_Co=256 

" Auto completion, trigger with <C-n>
set wildmenu

" Set the commands to save in history default number is 20.
set history=1000
"set undofile
